### ISSUE TITLE
Any way to control switch directly?

### ISSUE THREAD

**Issue by JetForMe** [tlyakhov/python-decora_wifi#3]
Is there any way to control the switch directly, without going out to leviton.com?

**Comment by rogersmj** [comment]
I'm wondering this too. I bought one of these and during my testing I was dismayed to find out that every command goes through the Leviton cloud. If we can find a way to control directly within the LAN that would make these switches way more interesting.

**Comment by tlyakhov** [comment]
Oops sorry I missed these, guys. Yes, this is a Leviton security measure - the switches are completely locked down and designed to only communicate with Leviton's cloud APIs. No LAN support.

**Comment by yeroca** [comment]
Seems a bit crazy for Leviton not to provide a LAN API capability. Is it likely that Leviton will support these devices 30 years from now, when we're living in the age of fusion power and flying cars?  (the last part is j/k)

**Comment by JetForMe** [comment]
> Oops sorry I missed these, guys. Yes, this is a Leviton security measure - the switches are completely locked down and designed to only communicate with Leviton's cloud APIs. No LAN support.

Yeah, that's such a misguided attempt at security. It's less secure than a local API. Oh well, I'll look for other products. Thanks for your work, though!

**Comment by JetForMe** [comment]
> Seems a bit crazy for Leviton not to provide a LAN API capability. Is it likely that Leviton will support these devices 30 years from now, when we're living in the age of fusion power and flying cars? (the last part is j/k)

This is the biggest problem with cloud-only products.
