### ISSUE TITLE
Fails to connect to leviton

### ISSUE THREAD

**Issue by thinksilicon** [tlyakhov/python-decora_wifi#4]
Hey,
I've pip installed the dacora-wifi package and tried to run the cli-example. Unfortunately it seems to fail right during the authentication. I've ensured I'm using the right credentials. Does this error-message make any sense to you?

``Traceback (most recent call last):``
``  File "dacora-cli.py", line 23, in <module>``
``    session.login(decora_email, decora_pass)``
``  File "/home/pi/.local/lib/python2.7/site-packages/decora_wifi/__init__.py", line 84, in login``
``    self.user = Person(self, login_json['userId'])``
``  File "/home/pi/.local/lib/python2.7/site-packages/decora_wifi/models/person.py", line 13, in __init__``
``    super(Person, self).__init__(session, model_id)``
``TypeError: super() argument 1 must be type, not classobj``

**Comment by tlyakhov** [comment]
Please use Python 3+... I haven't tested with Python 2.7, but I'm sure there would be compatibility issues.

**Comment by thinksilicon** [comment]
Oh, thanks, that was a quick fix. And yeah, works nicely with python3. Maybe add a line to the readme, so people will know.

Thanks again!
