### ISSUE TITLE
Execute Activity

### ISSUE THREAD

**Issue by dwclarknu** [tlyakhov/python-decora_wifi#7]
I have a stored Activity in Leviton I am trying to execute. I am able to find the activity. When I call <activity>.execute(session) I am receiving a 401 Unauthorized back from Leviton. The credentials I am using are the only Levity credentials and have Owner permissions. They are the same permissions I am using in the My Leviton app as well as Google Home so I know they have rights.

**Comment by tlyakhov** [comment]
Hm, interesting. I haven't played around with that part of the object model very much. Can you show the code you're using? I'll try to reproduce locally. Maybe some tweaking around Permission/ResidentialPermission is necessary.

**Comment by dwclarknu** [comment]
`from decora_wifi import DecoraWiFiSession
from decora_wifi.models.person import Person
from decora_wifi.models.residential_account import ResidentialAccount
import sys


if len(sys.argv) < 5:
    print('Usage: ./cli-test.py [email] [pass] [RESIDENCE] [ACTIVITY]')

decora_email = sys.argv[1]
decora_pass = sys.argv[2]
decora_residence = sys.argv[3]
decora_activity = sys.argv[4]

session = DecoraWiFiSession()
session.login(decora_email, decora_pass)

# Gather all the available devices...

perms = session.user.get_residential_permissions()
for permission in perms:
    acct = ResidentialAccount(session, permission.residentialAccountId)
    for res in acct.get_residences():
        if(res.name == decora_residence):
            print("Residence: Found")
            for activity in res.get_residential_activities():
                if(activity.name == decora_activity):
                    print("Activity: Found")
                    activity.execute(session)
                else:
                    print("Activity: Not found")

Person.logout(session)
`

**Comment by dwclarknu** [comment]
`from decora_wifi import DecoraWiFiSession
from decora_wifi.models.person import Person
from decora_wifi.models.residential_account import ResidentialAccount
import sys


if len(sys.argv) < 5:
    print('Usage: ./cli-test.py [email] [pass] [RESIDENCE] [ACTIVITY]')

decora_email = sys.argv[1]
decora_pass = sys.argv[2]
decora_residence = sys.argv[3]
decora_activity = sys.argv[4]

session = DecoraWiFiSession()
session.login(decora_email, decora_pass)

perms = session.user.get_residential_permissions()
for permission in perms:
    acct = ResidentialAccount(session, permission.residentialAccountId)
    for res in acct.get_residences():
        if(res.name == decora_residence):
            print("Residence: Found")
            for activity in res.get_residential_activities():
                if(activity.name == decora_activity):
                    print("Activity: Found")
                    activity.execute(session)
                else:
                    print("Activity: Not found")

Person.logout(session)
`

**Comment by tlyakhov** [comment]
This is a bit off the top of my head, can you try this: `activity.execute(session, { 'id': activity.id })` and see if it works? If it throws an error about `activity` not having an id, you may need to add an explicit `id` getter to BaseModel, I don't remember if there is one or not.

**Comment by dwclarknu** [comment]
That was it...thank you! Working beautifully
